services:

  restate:
    image: docker.restate.dev/restatedev/restate:latest
    ports:
      - "8081:8080"
      - "9070:9070"
      - "9071:9071"
    healthcheck:
      test: ["CMD", "restate", "--yes", "services", "list"]
      interval: 3s
      retries: 20

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: cashi
      POSTGRES_USER: cashi
      POSTGRES_PASSWORD: cashi
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cashi -d cashi"]
      interval: 3s
      retries: 20

  fees-app:
    build: .
    ports:
      - "8080:8080"
      - "9080:9080"   # <-- I need this to register the restate SDK for the app
    environment:
      SERVER_PORT: 8080
      RESTATE_SDK_PORT: 9080
      RESTATE_INGRESS_URL: http://restate:8080
      DB_URL: jdbc:postgresql://postgres:5432/cashi
      DB_USER: cashi
      DB_PASSWORD: cashi
    depends_on:
      postgres: { condition: service_healthy }
      restate: { condition: service_healthy }
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/actuator/health || exit 1"]
      interval: 5s
      retries: 20

  # restate has no automatic service registery so I added this cli register
  register:
    image: docker.restate.dev/restatedev/restate-cli:latest
    environment:
      RESTATE_ADMIN_URL: http://restate:9070
    depends_on:
      fees-app: { condition: service_healthy }
    restart: on-failure
    command: >
      --yes deployments register http://fees-app:9080
